
name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - develop
pr: none

stages:
- template: build/build.yaml
  parameters: 
    docker: "$(docker)"

- template: stages/release-stage.yaml
  parameters:
    migrations: ${{ variables.Migrations }}



  