jobs:
- deployment: Deploy
  displayName: 'Deploy '
  dependsOn: 
  - Integration
  - Migration
  condition: and(in(dependencies.Migration.result, 'Succeeded', 'Skipped'), in(dependencies.Integration.result, 'Succeeded', 'Skipped'))
  environment: QA
  strategy:                 
    runOnce: 
      deploy: 
        steps:
        - bash: |
            echo "Deploy dev"