jobs:
- deployment: Deploy
  displayName: 'Deploy '
  condition: Skipped()
  environment: QA
  strategy:                 
    runOnce: 
      deploy: 
        steps:
        - bash: |
            echo "Deploy dev"