parameters:
  name: deps
  type: object
  default: 
  - Integration


jobs:
- deployment: Deploy
  displayName: 'Deploy'
  dependsOn: Integration
  condition: in(dependencies.Integration.result, 'Succeeded', 'Skipped')
  environment: QA
  strategy:                 
    runOnce: 
      deploy: 
        steps:
        - bash: |
            echo "Deploy dev"