jobs:
- deployment: Deploy
  displayName: 'Deploy'
  dependsOn:
  - Integration
  - Migration
  condition: in(dependencies.result, 'Succeeded', 'Skipped')
  environment: QA
  strategy:                 
    runOnce: 
      deploy: 
        steps:
        - bash: |
            echo "Deploy dev"