parameters:
- name: migrations # name of the parameter; required
  type: string # data type of the parameter; required
  default: true

jobs:
- job: Integration
  condition: and(succeeded(), ne(variables['IntegrationTests'], 'false'))
  displayName: 'Integration Tests'