parameters:
- name: 'migrations'
  default: 'false'
  type: string

stages:
- stage: dev
  displayName: dev
  dependsOn: Build
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/dev'))
  jobs:
  - template: /release/integration.yaml
    parameters:
      migrations: ${{ variables.Migrations }}
  - ${{ if eq(parameters.migrations, true) }}:
    - template: /release/migration.yaml
  - template: /release/deploy.yaml
    parameters: 
      dependencies:
        - job : Integration

- stage: staging
  displayName: staging
  dependsOn: Build
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: /release/integration.yaml
    parameters:
      migrations: (${{ variables.Migrations }})
  - ${{ if eq(parameters.migrations, true) }}:
    - template: /release/migration.yaml
  - template: /release/deploy.yaml
    parameters:
      approvals: 'QA'

